version: "3"

vars:
  BIN: findex
  PKG: ./...
  CMD: ./cmd/findex

tasks:
  run:
    desc: Run locally
    cmds:
      - go run {{.CMD}}

  build:
    desc: Build binary
    cmds:
      - mkdir -p bin
      - go build -o bin/{{.BIN}} {{.CMD}}

  test:
    desc: Run tests
    cmds:
      - go test {{.PKG}}
